//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emulator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1454418802_resultset_next {
            get {
                object obj = ResourceManager.GetObject("_1454418802_resultset_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1454418842_resultset_last {
            get {
                object obj = ResourceManager.GetObject("_1454418842_resultset_last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1461522452_document_16 {
            get {
                object obj = ResourceManager.GetObject("_1461522452_document_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1461522515_folder_16 {
            get {
                object obj = ResourceManager.GetObject("_1461522515_folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1461522528_save_16 {
            get {
                object obj = ResourceManager.GetObject("_1461522528_save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1461522691_info_16 {
            get {
                object obj = ResourceManager.GetObject("_1461522691_info_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Значок).
        /// </summary>
        internal static System.Drawing.Icon _1464246333_cpu_processor {
            get {
                object obj = ResourceManager.GetObject("_1464246333_cpu_processor", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ; Тип записи
        ///; ИНСТРУКЦИЯ [ОПЕРАНД1] [ОПЕРАНД2]
        ///; r - регистр
        ///; d - число
        ///; v - значение (регистр или число)
        ///; l - метка, название подпрограммы
        ///; a - массив
        ///
        ///add r v
        ///adc r v
        ///and r v
        ///bsf r v
        ///bsr r v
        ///bt r d
        ///btc r d
        ///btr r d
        ///bts r d
        ///call l
        ///cbw r
        ///clc
        ///cld
        ///cli
        ///cmc
        ///cmp v v
        ///cwd
        ///dec r
        ///div r
        ///idiv r
        ///enter
        ///imul r
        ///inc r
        ///int d
        ///je l
        ///jz l
        ///jnz l
        ///jne l
        ///jc l
        ///jnae l
        ///jb l
        ///jnc l
        ///jae l
        ///jnb l
        ///jp l
        ///jnp l
        ///js l
        ///jns l
        ///jo l
        ///jno l
        ///ja l
        ///jnbe l
        ///jna l
        ///jbe l
        ///jg l
        ///jnle l
        ///jge l
        ///jnl l
        ///jl l [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string instructions {
            get {
                return ResourceManager.GetString("instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shape_square_16 {
            get {
                object obj = ResourceManager.GetObject("shape_square_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
